'''
Created on May 4, 2018
 
@author: Rishabh Bakshi
'''
 
import time

from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.keys import Keys


# driver = webdriver.Firefox(executable_path='C:/Users/Rishabh Bakshi/Downloads/Compressed/geckodriver-v0.20.1-win32/geckodriver.exe')
# This block of code is used to block the notification popup which is generated by site
options = webdriver.ChromeOptions()
options.add_argument("--disable-notifications")

# to open firefox webbrowser and maximize the window
driver = webdriver.Chrome(executable_path="C:/Users/admin/Downloads/chromedriver_win32/chromedriver.exe", chrome_options=options)
driver.maximize_window()
 
# Implicit Wait when element is taking time to load
driver.implicitly_wait(20)
 
# connect to the specific ip address
driver.get("http://www.facebook.com")
 
# Login to Facebook
driver.find_element_by_id("email").clear()
driver.find_element_by_id("email").send_keys("bakshirishab90@gmail.com")
driver.find_element_by_id("pass").clear()
driver.find_element_by_id("pass").send_keys("1109@Root")
driver.find_element_by_id("loginbutton").click();
 
# Waiting time 
time.sleep(5)
 
# Click on Profile Name
driver.find_element_by_xpath("//a[@title='Profile']").click()
 
# Click on 'Friends' option
driver.find_element_by_xpath("//a[@data-tab-key='friends']").click()
 
'''
I defined a blank list 
it is used to store 'profile name' of  each friend 
'''
listProfileName = []
 
# Flag to check the visibility of 'Films' Section (this section's placing is just after the friend list)
movieSection = False
 
# Loop to check the 'Films' Section  in each iteration
while movieSection == False:
    try:
        # Taking the element of 'Films' Section 
        movieElem = driver.find_element_by_xpath("//a[text()='Films']")
        print(movieElem.text)
        
        # Check the element of 'Films' Section 
        if movieElem.text == "Films":
            movieSection = True
            break
        else:
            continue
    except Exception:
        # Get the list of all friends
        profilePicList = driver.find_elements_by_xpath("//div[@data-testid='friend_list_item']/a")
        for profilePic in profilePicList:
            # Get the profile URL of friend in each iteration of the loop by using 'href' attribute
            profileURL = profilePic.get_attribute("href")
            finalProfileName = ''
            
            '''
            We have got two type profile URL 
            1. Which contains Profile name 
            2. Which contains Profile Id
            So we have added both check by using if-else
            '''
            if profileURL.find('profile.php?id=') == -1:
                finalProfileName = profileURL[profileURL.index('.com/') + len('.com/'):profileURL.index('?')]
            else:
                finalProfileName = profileURL[profileURL.index('profile.php?id=') + len('profile.php?id='):profileURL.index('&')]
            
            # Append the list by the profile name
            listProfileName.append(finalProfileName)
        
        # Press Control + END to get the invisible friend on the current visible portion on the page
        profilePicList[len(profilePicList) - 1].send_keys(Keys.CONTROL + " " + Keys.END);
 
# Then we have added the filtered list by using 'Set' [REmove all duplicate name]
filteredFriendSet = set(listProfileName)
 
'''
Now its time to send message to each and every friend of your friend-list
For this purpose 'What do you have to do'
 
1. You have to apply a for loop to traverse each and every element of the set 
2. Make the Message URL of friend 
3. Hit to the  browser
4. Paste the message
 
Note :- In case program is getting error while execution. I have added exception handling.
=========================== WOW! Here you are. It's done =======================
'''
for item in filteredFriendSet:
    try:
        driver.get("https://www.facebook.com/messages/t/{userName}".format(userName=item))
        driver.switch_to_active_element().send_keys("HI, \n its a test message \n please don't reply \n")
        time.sleep(1)
    except UnexpectedAlertPresentException:
        driver.switch_to_alert().accept()  
    except Exception:
        continue
    
# To close the browser
driver.quit()
